services:
  - name: certifica-utf-service-registry
    type: pserv
    env: docker
    repo: https://github.com/OficinaDeSoftware/certifica-utf-service-registry.git
    branch: main

  - name: certifica-utf-gateway
    type: web
    env: docker
    repo: https://github.com/OficinaDeSoftware/certifica-utf-gateway.git
    branch: main
    healthCheckPath: /
    envVars:
      - key: EUREKA_SERVER_URL
        value: ${EUREKA_SERVER_URL}
    plan: free

  - name: certifica-utf-auth
    type: pserv
    env: docker
    repo: https://github.com/OficinaDeSoftware/certifica-utf-auth.git
    branch: master
    envVars:
      - key: BROKER_EMAIL
        value: ${BROKER_EMAIL}
      - key: GOOGLE_CLIENTE_ID
        value: ${GOOGLE_CLIENTE_ID}
      - key: MONGO_URL
        value: ${MONGO_URL}
      - key: TOKEN_SECURITY_JWT
        value: ${TOKEN_SECURITY_JWT}
      - key: UTFPR_BASEURL
        value: ${UTFPR_BASEURL}
      - key: EUREKA_SERVER_URL
        value: ${EUREKA_SERVER_URL}

  - name: certifica-utf-back-end
    type: pserv
    env: docker
    repo: https://github.com/OficinaDeSoftware/certifica-utf-back-end.git
    branch: main
    envVars:
      - key: BROKER_EMAIL
        value: ${BROKER_EMAIL}
      - key: MONGO_URL
        value: ${MONGO_URL}
      - key: RABITMQ_ADDRESS
        value: ${RABITMQ_ADDRESS}
      - key: EUREKA_SERVER_URL
        value: ${EUREKA_SERVER_URL}